version: '2'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    network_mode: host
  prometheus:
    build: prometheus
    volumes:
      - prom_data:/prometheus
    network_mode: host
  loki:
    image: grafana/loki:2.0.0
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: host
  promtail:
    build: promtail
    volumes:
      - ${HOME}/logs-chia:/var/log/chia
    command: -config.file=/etc/promtail/config.yml
    network_mode: host
  grafana:
    build: grafana
    network_mode: host
volumes:
  prom_data:
