{
 "title": "Chia",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, instance)"
    }
   },
   {
    "name": "mounts",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, mountpoint)"
    }
   },
   {
    "name": "disks",
    "query": {
     "query": "label_values(node_disk_io_time_seconds_total, device)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temp dir bytes used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/plotting\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/plotting\"}"
    }
   ]
  },
  {
   "title": "Plotter Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"plotter\"}!=\"uniform sort\""
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - node_memory_Buffers_bytes{instance=\"$node\"} - node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Thoughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=\"$node\"}[$__rate_interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}